# Generated by Django 5.0.6 on 2024-12-09 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apli', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='metodo_pago',
        ),
        migrations.DeleteModel(
            name='MetodoPago',
        ),
    ]
